# This action creates downstream PRs for PRs with backport labels defined.
# See docs here: https://github.com/hashicorp/backport-assistant

name: Backport Assistant Runner

on:
  pull_request_target:
    types:
      - closed
      - labeled
    branches:
      - main
      - 'releases/*.*.x'

jobs:
  backport:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    container: hashicorpdev/backport-assistant:0.2.3
    steps:
      - name: Run Backport Assistant for stable-website
        run: |
          backport-assistant backport -merge-method=rebase -auto-merge
        env:
          BACKPORT_LABEL_REGEXP: "type/docs-(?P<target>cherrypick)"
          BACKPORT_TARGET_TEMPLATE: "stable-website"
          GITHUB_TOKEN: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
      - name: Run Backport Assistant for release branches
        run: |
          backport-assistant backport -merge-method=rebase -auto-merge
        env:
          BACKPORT_LABEL_REGEXP: "backport/(?P<target>\\d+\\.\\d+)"
          BACKPORT_TARGET_TEMPLATE: "release/{{.target}}.x"
          GITHUB_TOKEN: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
